### ISSUE TITLE
"No valid templates found"

### ISSUE THREAD

**Issue by agbgt** [Ixaruz/Luna-App#10]
Basically what it says on the title. I set up and installed it exactly like you described, with enctemplate.zip being extracted into the enctemplate folder. But still, when I try to dump any island, it gives me this error message. I tried fiddling around with all sorts of things but I can't get it to work, and I'm not sure what to do.

**Comment by Ixaruz** [comment]
That message shows up when literally 0 files are inside the template folder. Please make sure the folder name is 100% correct. If necessary, send me a screenshot of the folder and path and I might find the issue.

**Comment by agbgt** [comment]
> That message shows up when literally 0 files are inside the template folder. Please make sure the folder name is 100% correct. If necessary, send me a screenshot of the folder's contents and path and I might find the issue.

Yeah sure thing 

![Screenshot (5)](https://github.com/Ixaruz/Luna-App/assets/39567998/bed807e4-d493-4b21-83b6-bec6da48429d)

I'll put a screenshot of the foldern and path for you. I hope this helps. Sorry about the bother!

**Comment by agbgt** [comment]
Yeah sure thing I'll post a screenshot of the contents and path here. Sorry for the bother!

![Screenshot 2024-01-11 231912](https://github.com/Ixaruz/Luna-App/assets/39567998/10b924f0-a73a-4437-af4d-809b00be65a3)

**Comment by agbgt** [comment]
Sure thing here's a screenshot of the path and folder, I hope this helps!

![Screenshot 2024-01-11 232312](https://github.com/Ixaruz/Luna-App/assets/39567998/d58ca54a-76d5-48c3-834b-c39f1d8197fe)

**Comment by Ixaruz** [comment]
That looks okay; I would assume another thing is possible: the error can also show up when a subfolder is empty. So that could mean, that either one of the Villager folders is empty OR that there might be some hidden file/folder? It all seems kind of unlikely.

Another idea that I have is that something is interfering with Luna reading from the SD card; i.e. some other app could be preventing read access, but then I'd at least expect Luna to fail out entirely...
You could try disabling all kinds of other homebrew services/apps and see if that changes anything.

I don't really have a clue on how to solve this issue right now, as it must be some factor on your end.

If you are willing to help me investigate this further, please let me know and we'll continue this conversation some other time . I will need to head to bed now.

**Comment by agbgt** [comment]
Absolutely, I'm more than willing to investigate this together. I'm more than happy to try anything out that you suggest and provide any further information.

Have a good rest, thank you so much for your consideration and time!

**Comment by Ixaruz** [comment]
That is very bizarre that Windows finds the files in the filesystem of the SD card and your switch doesn't. I don't think it's luna's issue (though thats an easy thing to say). 
something must be wrong with the SD card? I assume you tried many things already, like deleting the luna directory from the config folder and copying it there again...

could you try copying the files onto the SD card via ftp or some other method?

**Comment by Ixaruz** [comment]
From what I read online, another very likely issue could be that your SD is formatted as exFAT and not FAT32. Its supposedly very wonky on switch

**Comment by agbgt** [comment]
Just checked and the SD card is definitely FAT32. Never had this sort of issue before. I could try a different SD card? I don't know what FTP is but I can try to figure it out.

**Comment by Ixaruz** [comment]
https://nh-server.github.io/switch-guide/faq/#my-homebrew-is-not-showing-up-on-the-menu
![Screenshot](https://github.com/Ixaruz/Luna-App/assets/44379110/584cf83a-7d1c-42dc-855b-bc1adfa8ce31)

I know you aren't a mac user, but you should try this first before setting up an FTP Server on your switch.

**Comment by agbgt** [comment]
That archive bit fix worked! It finally let me dump islands!

**Comment by Ixaruz** [comment]
whoop, glad it works now!

**Comment by Ixaruz** [comment]
feel free to close the issue if there is nothing else wrong :^)
