### ISSUE TITLE
Once the island is dumped, do you have the character, its objects or its designs?

### ISSUE THREAD

**Issue by Danimariopapelhacker** [Ixaruz/Luna-App#11]

**Comment by Ixaruz** [comment]
No items, but all designs and characters.

**Comment by Danimariopapelhacker** [comment]
I love the app that you have created, it has spectacular merit to create an app that no one has created, continue with the project and please can you make a YouTube video 🙏

**Comment by Danimariopapelhacker** [comment]
Ixaruz do you know how you can play online games in atmosphere
