### ISSUE TITLE
Atmosphere crash

### ISSUE THREAD

**Issue by keropppi** [Ixaruz/Luna-App#12]
Whenever i try to get the dump for a island whenever i press the dump button armosphere crashes and i have to reset the whole system. Anyone know why, or how to fix it?

**Comment by Danimariopapelhacker** [comment]
1. make sure you are on the latest version of atmosphere 2. that your SD is not corrupted and is formatted in fat32 3. that you have the enctemplate

**Comment by Danimariopapelhacker** [comment]
Close the Issue

**Comment by Ixaruz** [comment]
issue was related to using an out-of-date version of Luna.
