### ISSUE TITLE
Luna tries to connect to nintendo servers

### ISSUE THREAD

**Issue by Tracheaa** [Ixaruz/Luna-App#13]
Whenever I try to visit a dream address Luna tries to connect to the internet and when that happens I get an error telling me that I couldn't connect to the servers.

**Comment by DJanielFF** [comment]
you have to use cfw sysnand not emunand since emunand cannot connect to nintendo services

**Comment by Danimariopapelhacker** [comment]
Close the Issue

**Comment by Tracheaa** [comment]
I can't connect to cfw  sysnand it's corrupted

**Comment by DJanielFF** [comment]
> I can't connect to cfw  sysnand it's corrupted

I will help you solve it, don't worry

**Comment by DJanielFF** [comment]
I am going to give you a link with the steps to follow to be able to use sysnandcfw https://nh-server.github.io/switch-guide/

**Comment by Albaa10** [comment]
> > Close the Issue
> 
> 
> 
> 
> 
> 
> 
> > I am going to give you a link with the steps to follow to be able to use sysnandcfw https://nh-server.github.io/switch-guide/
> 
> 
> 
> I'm still getting an error but I got sysnandcfw  to work what should I do

I'm sorry, it won't let me respond, Ixaruz has to help you.

**Comment by Tracheaa** [comment]
oh okay

**Comment by Tracheaa** [comment]
I figured out an alternative, thanks for the help!
