### ISSUE TITLE
No valid template when trying to dump an island

### ISSUE THREAD

**Issue by sosaau** [Ixaruz/Luna-App#14]
the island name comes up but when i try and dump the island i get that error code could someone lead me in a direction to fix the issue.

**Comment by Ixaruz** [comment]
Stupid questions bla bla:
1. Did you install the ``enctemplate`` as the guide in the README told you to?
2. If the path of the template is right and everything *should* work (but just doesn't), you may need to fix archive bits. https://github.com/Ixaruz/Luna-App/issues/10#issuecomment-1890730961

**Comment by DJanielFF** [comment]
> Stupid questions bla bla:
> 1. Did you install the ``enctemplate`` as the guide in the README told you to?
> 2. If the path of the template is right and everything *should* work (but just doesn't), you may need to fix archive bits. https://github.com/Ixaruz/Luna-App/issues/10#issuecomment-1890730961

Ixaruz, congratulations on your work. Will you continue with the moon app project?

**Comment by sosaau** [comment]
I've followed your steps and cleared archive and it still doesn't work but okay :)

**Comment by DJanielFF** [comment]
> I've followed your steps and cleared archive and it still doesn't work but okay :)

first of all you use sysnand cfw

**Comment by sosaau** [comment]
i am using sys??

**Comment by DJanielFF** [comment]
> i am using sys??

Let's do one thing, don't close the issue and I'll help you until it's resolved.

**Comment by sosaau** [comment]
![image](https://github.com/Ixaruz/Luna-App/assets/167495890/b289ff99-bdbd-4a4a-bfd8-09078f45fb95)

**Comment by sosaau** [comment]
sysmmc

**Comment by sosaau** [comment]
yes for both but and when i travel to peoples islands i can see their name of the island pop up in the dump but i can't actually dump their island without getting that error

**Comment by Ixaruz** [comment]
> I've followed your steps and cleared archive and it still doesn't work but okay :)

If you say, you "cleared archive", does that mean you did "Unset archive bit" or did you "Fix archive bit" in hekate?

The only other obvious reason why the "no valid template" error occurs is, if the template cannot be found at all. You can check if the switch file system picks up the enctemplate folder at all by going to the config/luna folder in the homebrew menu.
If it doesn't show up at all, something is wrong with the archive bits/file system.

You could also provide a screenshot or multiple screenshots showing your SD:/config/luna and SD:/config/luna/enctemplate folders, so I could see if you installed the template correctly :)

**Comment by DJanielFF** [comment]
> yes for both but and when i travel to peoples islands i can see their name of the island pop up in the dump but i can't actually dump their island without getting that error 

OK, you have copied the files wrong, so you have to do a fix archive bit and copy the files to their place on the corresponding SD

**Comment by Ixaruz** [comment]
> ![image](https://private-user-images.githubusercontent.com/167495890/323925792-b289ff99-bdbd-4a4a-bfd8-09078f45fb95.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MzIyMzQsIm5iZiI6MTcxMzUzMTkzNCwicGF0aCI6Ii8xNjc0OTU4OTAvMzIzOTI1NzkyLWIyODlmZjk5LWJkYmQtNGE0YS1iZmQ4LTA5MDc4ZjQ1ZmI5NS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTlUMTMwNTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTkzMGYwNGExYmJjNzE2OTYyZDcyOTc2ZTg4YTA4MTgxMDFlMGZlM2VkZWMxY2U4ZDZhNDNkNDk3YTgwMDljZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zDSSbESDOKhlkYHDB959VhiolmGIESodWbA9Ip0aVUA)

Please move the enctemplate to the right location.
Your path in the bottom left says ``sdmc:/config/luna/config/enctemplate`` when it should say ``sdmc:/config/luna/enctemplate``.

**Comment by sosaau** [comment]
yeah i’ll follow up with this tomorrow it’s currently 11:18 pm i’m also
just wondering when i load into a island why can’t i go online do you know
how i can make it so i can?

**Comment by DJanielFF** [comment]
ixaruz thank you very much for your help the online now works for me

**Comment by sosaau** [comment]
can you tell me the steps to get online with a dream island?

**Comment by Ixaruz** [comment]
you have to use your own save file as a template. for that, you dump your savefile with JKSV - or any other save manager - and you copy the contents to ``sdmc:/config/luna/enctemplate``.

The more tedious way would be to use NHSE after you made the dump with the included enctemplate. I will not go into detail on how to do it, bc it's annoying to do and if you really wanna do it, then you can text me about it later. I would prefer if you do the first method.

**Comment by Ixaruz** [comment]
oh and btw the Dream Address you mentioned in the other issue (DA-6682-0320-9029) is not currently online.

**Comment by DJanielFF2** [comment]
> you have to use your own save file as a template. for that, you dump your savefile with JKSV - or any other save manager - and you copy the contents to ``sdmc:/config/luna/enctemplate``.
> 
> 
> 
> The more tedious way would be to use NHSE after you made the dump with the included enctemplate and copy the authentication data from your own save file to your dump. I will not go into detail on how to do it, bc it's annoying to do and if you really wanna do it, then you can text me about it later. I would prefer if you do the first method.

You are the best and very kind for helping others like you have taught me to pay you

**Comment by DJanielFF2** [comment]
Is there a way to pay you?

**Comment by sosaau** [comment]
could you please show a step by step guide on how to transfer the save profile data so you can go online.

**Comment by Albaa10** [comment]
> could you please show a step by step guide on how to transfer the save profile data so you can go online. 

I am DJanielFF in a different account

**Comment by sosaau** [comment]
that's all good are you able to make a step by step guide since i'm pretty new to modding on the switch and have no clue

**Comment by Albaa10** [comment]
> that's all good are you able to make a step by step guide since i'm pretty new to modding on the switch and have no clue 

Ok, to be able to connect to the internet you need to do the following steps: 1.delete the enctemplate from the sd that is given in the luna app repository 2.With a homebrew app like JKSV or checkpoint you save or dump animal crossing new horizons 3 The files that are generated will go in SD/Config/Luna/Enctemplate and what you have left is to enter the dream that you want to have and when you dump the island that you want you restore it with JKSV or checkpoint and you would have the island that you want. you wanted online

**Comment by sosaau** [comment]
i mean as i already have a dream island i want and i know how to restore it onto my switch but the problem im having is when i load the island up i can't use online services like fly to another island or dream for an address like it won't let me use online services?

**Comment by Albaa10** [comment]
> i mean as i already have a dream island i want and i know how to restore it onto my switch but the problem im having is when i load the island up i can't use online services like fly to another island or dream for an address like it won't let me use online services? 

Of course that is because you used the enctemplate from this repository, you have to use your own files from your saved game of Animal Crossing New Horizons

**Comment by sosaau** [comment]
no i need to restore to my ordinal island then dream then restore? the new island ??

**Comment by Ixaruz** [comment]
as described in my previous comment:
> you have to use your own save file as a template. for that, you dump your savefile with JKSV - or any other save manager - and you copy the contents to `sdmc:/config/luna/enctemplate`.
> 
> The more tedious way would be to use NHSE after you made the dump with the included enctemplate and copy the authentication data from your own save file to your dump. I will not go into detail on how to do it, bc it's annoying to do and if you really wanna do it, then you can text me about it later. I would prefer if you do the first method.

If you already have a dump, that was made from this repository's enctemplate, it wont hold any authentication data (to go online).
This is because I obviously do not include any data in the enctemplate, that could be used to trace back to my Nintendo Account.

this can be fixed manually, but as i stated, is tedious, annoying, difficult. I do not want to go into detail about it, as - no offense - I don't trust you to do it properly.

Please create a dump again yourself by backing up your save file with JKSV, copying those files into the sdmc:/config/luna/enctempate/ folder and running Luna, when you visit that island.

If you want to do it in a Discord chat/call, you can add me here https://discord.com/invite/EKCzk2sv

and a side note: @Albaa10 I blocked your other accounts on purpose, as you're being incredibly unhelpful and annoying.
Please don't send download links to dumps in issues, don't ask questions that a google search can provide answers for, don't annoy people like kwsch at NHSE about anything that happens with MY application. They don't have anything to do with my App, besides the fact that i shout them out as a helpful resource.

**Comment by Ixaruz** [comment]
we managed to put the enctemplate in the right directory on the SD-Card.
