### ISSUE TITLE
ixaruz application are you going to continue with the luna App proyect?

### ISSUE THREAD

**Issue by DJanielFF** [Ixaruz/Luna-App#15]
I mean supporting the DLC

**Comment by sosaau** [comment]
![5](https://github.com/Ixaruz/Luna-App/assets/167495890/36f233ca-3825-429a-9a2b-2f5c0f06dea7)
![6](https://github.com/Ixaruz/Luna-App/assets/167495890/7199c71f-00f3-4166-a030-5de571526b5c)

**Comment by DJanielFF** [comment]
> ![5](https://github.com/Ixaruz/Luna-App/assets/167495890/36f233ca-3825-429a-9a2b-2f5c0f06dea7)
> 
> ![6](https://github.com/Ixaruz/Luna-App/assets/167495890/7199c71f-00f3-4166-a030-5de571526b5c)
> 
> 

the enctemplate is correct have you tried going to hekate-tools-fix archive bit

**Comment by sosaau** [comment]
yes i have fixed the archive now im trying to load up acnh to see if it works now.

**Comment by DJanielFF** [comment]
> yes i have fixed the archive now im trying to load up acnh to see if it works now. 

okay good luck if it doesn't work I'll tell you more solutions

**Comment by sosaau** [comment]
i also have another question can you go online on the island you copy?

**Comment by DJanielFF** [comment]
> i also have another question can you go online on the island you copy?

The truth is that I don't know, I think it's possible, but you have to use NHSE or an enctemplate dumped from your saved. I'm sorry, in online issues, only ixaruz can help you.

**Comment by sosaau** [comment]
unfortunately it still didn't work have you got some saved dream islands that i can just download by chance?

**Comment by DJanielFF** [comment]
> unfortunately it still didn't work have you got some saved dream islands that i can just download by chance? 

Take a photo of the error that appears and I'll tell you the solution.

**Comment by sosaau** [comment]
![image](https://github.com/Ixaruz/Luna-App/assets/167495890/526aa3fc-48ff-4f79-9f94-64f26122292e)

**Comment by sosaau** [comment]
but their island name comes up it's weird

**Comment by DJanielFF** [comment]
> but their island name comes up it's weird 

ok you have the latest version of luna App?

**Comment by DJanielFF** [comment]
It works for me, I'm on the latest version of ATMOSPHERE

**Comment by sosaau** [comment]
doesn't seem to be working for me are you able just to send me a dream island dump pls it's most definitely on my end and you guys are doing a great job

**Comment by DJanielFF** [comment]
> doesn't seem to be working for me are you able just to send me a dream island dump pls it's most definitely on my end and you guys are doing a great job 

ok you dare one

**Comment by DJanielFF** [comment]
> doesn't seem to be working for me are you able just to send me a dream island dump pls it's most definitely on my end and you guys are doing a great job 

There is a 5.8GB package that has many islands, do you prefer the package or just one

**Comment by sosaau** [comment]
just want one island which is 

DA668203209029

**Comment by DJanielFF** [comment]
> seriously thank you 

no problem I will help you with everything

**Comment by DJanielFF** [comment]
The Package: https://mega.nz/file/0kwBnawI#hMRycb2Sg8SKhx0BcQFBqt03TeAz-9BICMmPYLkCMVE

**Comment by DJanielFF** [comment]
> just want one island which is 
> 
> DA668203209029

friend, I'm sorry, I was going to dump it but when I get on the island I see that I'm banned

**Comment by sosaau** [comment]
what's this dream island package i'm downloading then ?

**Comment by DJanielFF** [comment]
tell ixaruz to dump the island for you
