### ISSUE TITLE
fix ACNH online error using luna

### ISSUE THREAD

**Issue by DJanielFF** [Ixaruz/Luna-App#16]
Ixaruz, when I do the dump and restore it, I have the island I wanted but when I connect to the internet I get an error. It could be because the enctemplate is the one I downloaded from your repository?

**Comment by Ixaruz** [comment]
The enctemplate, that is provided with Luna, doesn't hold SaveNetPlayerID (ID and Password to authenticate yourself on the Animal Crossing Servers). you either have to copy it into your dump yourself, or you can use your own save file as a template (enctemplate) when using Luna to dump a save file.
