### ISSUE TITLE
Archive decryption problem

### ISSUE THREAD

**Issue by Ic-any** [Ixaruz/Luna-App#2]
I found that after extracting the file, it can be directly dragged into nShe without decrypting it again. If decrypted again, it will not be able to read.

**Comment by Ic-any** [comment]
So you don't need to use horizoncryptE.exe, this is really a great project.

**Comment by Ixaruz** [comment]
Yes, it's supposed to work without horizoncrypt. I made it a homebrew app, because it then can use a far bigger amount of memory, which is used for the encryption and decryption of the files.
