### ISSUE TITLE
The Chinese island name is too short to copy the island

### ISSUE THREAD

**Issue by Ic-any** [Ixaruz/Luna-App#3]
I visited a Chinese  name island, such as Herring Island. The word "herring" is a "—" on Luna, but the island name is too short for Luna to copy。

**Comment by Ic-any** [comment]
I don't know if this is because the system updated with 14.1.2

**Comment by Ic-any** [comment]
I'll test it because the name of the island is too short to copy

**Comment by Ixaruz** [comment]
the switch doesn't allow chinese characters in the folder names, thats why Luna replaces them with ____

**Comment by Ic-any** [comment]
I have some doubts. I went to the island of another machine. The island of the other machine is a two word name, and I also uploaded a dream. I saw the dream house number at the bottom of the map. The software dump is a dream house number instead of, for example, [da-000000000], but a string of normal dream codes. However, I found no files in the dump folder under the Luna folder of config.

**Comment by Ic-any** [comment]
![2022081108082300_s](https://user-images.githubusercontent.com/92638461/174445519-2e0415e9-b8d1-4993-a497-e99b7e4c6498.jpg)

**Comment by Ic-any** [comment]
For islands like this, I use the Internet to connect my own machine, but this will lead to the export of the dream empty file instead of the actual island after pressing dump

**Comment by Ixaruz** [comment]
Dumping an island you visit, that isn't a dream, it will always have the DA-0000-0000-0000.

Also I don't know why you didn't find the dump in the folders. If I cannot visit the same island, i cannot find out why that happened.

**Comment by Ic-any** [comment]
It should be an undetected bug. I will try to send you a video later

**Comment by Ixaruz** [comment]
okay thank you! I will try to figure out what went wrong

**Comment by Ic-any** [comment]
My friend tried to modify your open source project. I hope you can have a look. Thank you.
https://github.com/Wanghaoran86/Luna-Wang

**Comment by Ic-any** [comment]
This is about modifying the output file name. For example, the original Luna's [DA-0000-0000-0000] ———, Change to direct output to dream code DA-0000-0000-0000

**Comment by Ixaruz** [comment]
I don't think your issue has to do with the name of the folder. You mentioned that the file is empty / there are no files after pressing Dump. I'd like to look into that and I will therefore wait until you can send a video.

**Comment by Ic-any** [comment]
ok，bye！

**Comment by Ic-any** [comment]
ok

**Comment by Ic-any** [comment]
I tried once. Maybe the software may be triggered suddenly for this bug. Today is also the first time I encountered this problem, but in the process of trying, I found that it can be copied

**Comment by Ic-any** [comment]
![(GCTB4G(K85OVSUN9ENMYF7](https://user-images.githubusercontent.com/92638461/174448173-8c591e32-3703-40b4-b279-52fc6379c1ae.png)

**Comment by Ic-any** [comment]
![026}X VX%Y0TO({SQAQPQ A](https://user-images.githubusercontent.com/92638461/174448176-fdf7367f-cecc-4edd-a2d6-f91518a8f2eb.png)

**Comment by Ic-any** [comment]
But thank you for your answer. I will submit the questions I found later. Goodbye!
