### ISSUE TITLE
Designs placed on floor not dumped

### ISSUE THREAD

**Issue by Peddaahh** [Ixaruz/Luna-App#7]
Designs which are placed on the floor outside are not being dumped for me

**Comment by Ixaruz** [comment]
Could you provide more information? ideally the dream address you are having issues with, so I can check it out myself.

Usually both placed designs and items placed on furniture ([your other Issue](https://github.com/Ixaruz/Luna-App/issues/8)) are dumped, so I wouldn't know what is causing problems. If this is an issue with NHSE or the likes, know that placed designs and item layers exist.

**Comment by Peddaahh** [comment]
Yes, i forgot to update here, it is an NHSE issue thank you, placed designs can be imported with an odd way, but furniture on tables etc. are not recognized.. loading a dump with JKSV without NHSE shows no issues.

**Comment by Ixaruz** [comment]
you sure you changed the item layer before exporting/importing?

**Comment by Peddaahh** [comment]
Normally i should have exported and imported everything yes
