### ISSUE TITLE
Luna app only shows black screen

### ISSUE THREAD

**Issue by alewis3** [Ixaruz/Luna-App#9]
Running version 0.6.13 according to the homebrew menu, i tried deleting the app and reinstalling a fresh copy which did not work. Wondering if the app needs an update for switch version 16.1.0/AMS version 1.5.5 or is it working for other people?

**Comment by Ixaruz** [comment]
I'll try reproducing your issue and then likely have to recompile Luna with the latest libnx. Thanks for submitting an issue!

**Comment by Ixaruz** [comment]
Okay I'm on system version 16.1.0/AMS 1.5.5 and installed the 0.6.13 release of Luna. 
It still boots up perfectly fine.
Did you try it in handheld or docked mode? I don't have a dock to verify right now.

**Comment by Ixaruz** [comment]
And if you have the time:
could you try installing the latest build from [here](https://github.com/Ixaruz/Luna-App/actions/runs/6369546006).
This is built with the latest devkitpro image, containing libnx.

**Comment by alewis3** [comment]
Hi, thanks for responding! Sorry for my delayed response I forgot to check github, but I'll test this ASAP!

**Comment by alewis3** [comment]
Update: downloading that latest build artifact worked perfectly, so I will close this issue. Thank you for your help!

**Comment by Ixaruz** [comment]
I'll update the release file to use the same artifact, just to make sure no one else runs into this problem. Thank you for helping me out
